MedishcMVCProject/Models/Doctor/Degree.cs
namespace MedishcMVCProject.Models
{
    public class Degree : Base
    {
        public string Name { get; set; }
        public List<Doctor>? Doctors { get; set; }
    }
}

MedishcMVCProject/Models/Doctor/Doctor.cs
using MedishcMVCProject.Utilities;

namespace MedishcMVCProject.Models
{
    public class Doctor : Base
    {
        public string Image { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public decimal? ZodocRating { get; set; }
        public int? ReviewCount { get; set; }

        public string MainDescription { get; set; }
        public string? AdditionalDescription { get; set; }

        public int Age { get; set; }
        public GenderEnum Gender { get; set; }

        public int SpecialistId { get; set; }
        public Specialist Specialist { get; set; }

        public int? DegreeId { get; set; }
        public Degree? Degree { get; set; }

        public int? UniversityId { get; set; }
        public University? University { get; set; }

        public List<PriceList>? PriceLists { get; set; }
        public List<WorkingHours>? WorkingHours { get; set; }
        public List<Appointment> Appointments { get; set; } = new();
    }
}

MedishcMVCProject/Models/Doctor/OpeningHour.cs
using MedishcMVCProject.Utilities;

namespace MedishcMVCProject.Models
{
    public class OpeningHour : Base
    {
        public DayOfWeekEnum DayOfWeek { get; set; }
        public TimeSpan? OpenTime { get; set; }
        public TimeSpan? CloseTime { get; set; }

        public int DoctorId { get; set; }
        public Doctor Doctor { get; set; }
    }
}

MedishcMVCProject/Models/Doctor/PriceList.cs
namespace MedishcMVCProject.Models
{
    public class PriceList : Base
    {
        public string Name { get; set; }
        public decimal Price { get; set; }

        public int DoctorId { get; set; }
        public Doctor Doctor { get; set; }
    }
}

MedishcMVCProject/Models/Doctor/Specialist.cs
namespace MedishcMVCProject.Models
{
    public class Specialist : Base
    {
        public string Name { get; set; }
        public List<Doctor>? Doctors { get; set; }
    }
}

MedishcMVCProject/Models/Doctor/University.cs
namespace MedishcMVCProject.Models
{
    public class University : Base
    {
        public string Name { get; set; }
        public List<Doctor>? Doctors { get; set; }
    }
}

MedishcMVCProject/Models/Doctor/WorkingHours.cs
using MedishcMVCProject.Utilities;

namespace MedishcMVCProject.Models
{
    public class WorkingHours : Base
    {
        public DayOfWeekEnum DayOfWeek { get; set; }
        public TimeSpan? OpenTime { get; set; }
        public TimeSpan? CloseTime { get; set; }

        public int DoctorId { get; set; }
        public Doctor Doctor { get; set; }
    }
}

MedishcMVCProject/Areas/admin/Controllers/DoctorController.cs
using MedishcMVCProject.DAL;
using MedishcMVCProject.Models;
using MedishcMVCProject.Utilities;
using MedishcMVCProject.Utilities.Extensions;
using MedishcMVCProject.Utilities.Helpers;
using MedishcMVCProject.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace MedishcMVCProject.Areas.admin.Controllers
{
    [Area("Admin")]
    public class DoctorController : Controller
    {
        private readonly AppDbContext _context;
        private readonly IWebHostEnvironment _env;

        public DoctorController(AppDbContext context, IWebHostEnvironment env)
        {
            _context = context;
            _env = env;
        }
        public IActionResult List(string doctorName = null, string department = null)
        {
            List<GetDoctorVM> doctors = _context.Doctors
         .Include(x => x.WorkingHours)
         .Include(x => x.Specialist)
         .Select(d => new GetDoctorVM
         {
             Id = d.Id,
             Name = d.Name,
             Surname = d.Surname,
             SpecialistName = d.Specialist.Name,
             Image = d.Image,
             WorkingHours = d.WorkingHours.Select(wh => new WorkingHourVM
             {
                 DayOfWeek = wh.DayOfWeek,
                 OpenTime = wh.OpenTime,
                 CloseTime = wh.CloseTime
             }).ToList()
         }).ToList();
            doctors = Helpers.FilterByText(doctors, d => d.Name + " " + d.Surname, doctorName);
            doctors = Helpers.FilterByText(doctors, d => d.SpecialistName, department);
            return View(doctors);
        }
        public IActionResult Cards(string doctorName = null, string department = null)
        {
            List<GetDoctorVM> doctors = _context.Doctors
                .Include(x => x.Specialist)
                .Select(d => new GetDoctorVM
                {
                    Id = d.Id,
                    Name = d.Name,
                    Surname = d.Surname,
                    SpecialistName = d.Specialist.Name,
                    Image = d.Image,
                }).ToList();

            doctors = Helpers.FilterByText(doctors, d => d.Name + " " + d.Surname, doctorName);
            doctors = Helpers.FilterByText(doctors, d => d.SpecialistName, department);

            return View(doctors);
        }
        //ajax real search time...

        //public IActionResult FilterDoctors(string doctorName = null, string department = null)
        //{
        //    List<GetDoctorVM> doctors = _context.Doctors
        //        .Include(x => x.Specialist)
        //        .Select(d => new GetDoctorVM
        //        {
        //            Id = d.Id,
        //            Name = d.Name,
        //            Surname = d.Surname,
        //            SpecialistName = d.Specialist.Name,
        //            Image = d.Image,
        //        }).ToList();

        //    doctors = Helpers.FilterByText(doctors, d => d.Name + " " + d.Surname, doctorName);
        //    doctors = Helpers.FilterByText(doctors, d => d.SpecialistName, department);

        //    return PartialView("FilterDoctors", doctors); // yalnız kartları qaytarır
        //}

        public async Task<IActionResult> Profile(int? id)
        {
            if (id is null || id <= 0) return BadRequest();

            Doctor? doctor = await _context.Doctors
                .Include(d => d.Specialist)
                .Include(d => d.Degree)
                .Include(d => d.PriceLists)
                .Include(d => d.WorkingHours)
                .FirstOrDefaultAsync(d => d.Id == id);

            if (doctor is null) return NotFound();
            GetDoctorVM vm = new GetDoctorVM()
            {
                Image = doctor.Image,
                Name = doctor.Name,
                Surname = doctor.Surname,
                Review = doctor.ReviewCount,
                MainDescription = doctor.MainDescription,
                DegreeName = doctor.Degree?.Name,
                SpecialistName = doctor.Specialist?.Name,
                WorkingHours = doctor.WorkingHours.Select(oh => new WorkingHourVM
                {
                    DayOfWeek = oh.DayOfWeek,
                    OpenTime = oh.OpenTime,
                    CloseTime = oh.CloseTime
                }).ToList(),
                PriceLists = doctor.PriceLists.ToList()
            };

            return View(vm);
        }
        //CRUD


        public async Task<IActionResult> Create()
        {
            CreateDoctorVM doctorVM = new CreateDoctorVM()
            {
                Specialists = await _context.Specialists.ToListAsync()
            };

            return View(doctorVM);
        }
        [HttpPost]
        public async Task<IActionResult> Create(CreateDoctorVM doctorVM)
        {
            doctorVM.Specialists = await _context.Specialists.ToListAsync();

            if (!Helpers.HasDigit(doctorVM.Name))
            {
                ModelState.AddModelError(nameof(doctorVM.Name), "Name cannot contain digits");
            }

            if (!Helpers.HasDigit(doctorVM.Surname))
            {
                ModelState.AddModelError(nameof(doctorVM.Surname), "Surname cannot contain digits");
            }

            //**********BASLAMA VE BITME SAATININ 1 i DOLANDA OBRIDE DOLMALIDI AMMA SPANDA CIXMIR ERROR!*************

            if (doctorVM.WorkingHours != null)
            {
                foreach (WorkingHourVM? item in doctorVM.WorkingHours)
                {
                    bool hasOpen = item.OpenTime.HasValue;
                    bool hasClose = item.CloseTime.HasValue;

                    if (hasOpen != hasClose)
                    {
                        ModelState.AddModelError(
                            string.Empty,
                            $"{item.DayOfWeek} start or end time are missing!"
                        );
                    }
                }
            }






            if (!ModelState.IsValid)
            {
                return View(doctorVM);
            }

            bool result = doctorVM.Specialists.Any(s => s.Id == doctorVM.SpecialistId);

            if (!result)
            {
                ModelState.AddModelError(nameof(doctorVM.SpecialistId), "Specialist does not exist");
                return View(doctorVM);
            }



            if (!doctorVM.MainPhoto.ValidateType("image/"))
            {
                ModelState.AddModelError(nameof(CreateDoctorVM.MainPhoto), "file type is incorrect");
                return View(doctorVM);
            }

            if (!doctorVM.MainPhoto.ValidateSize(FileType.MB, 1))
            {
                ModelState.AddModelError(nameof(CreateDoctorVM.MainPhoto), "file must be less than 500kb");
                return View(doctorVM);
            }

            string image = await doctorVM.MainPhoto.CreateFileAsync(_env.WebRootPath, "assets", "images", "team", "full");


            Doctor doctor = new Doctor()
            {
                Name = doctorVM.Name.Capitalize(),
                Surname = doctorVM.Surname.Capitalize(),
                Age = doctorVM.Age,
                Gender = doctorVM.Gender,
                SpecialistId = doctorVM.SpecialistId.Value,
                Image = image,
                AdditionalDescription = doctorVM.AdditionalDescription,
                MainDescription = doctorVM.MainDescription,
                ReviewCount = doctorVM.ReviewCount,
                ZodocRating = doctorVM.ZodocRating,

                WorkingHours = Enum.GetValues(typeof(DayOfWeekEnum))
                                    .Cast<DayOfWeekEnum>()
                                    .Select(day =>
                                    {
                                        WorkingHourVM input = doctorVM.WorkingHours?.FirstOrDefault(x => x.DayOfWeek == day);
                                        return new WorkingHours
                                        {
                                            DayOfWeek = day,
                                            OpenTime = input?.OpenTime,
                                            CloseTime = input?.CloseTime
                                        };
                                    }).ToList(),

            };




            await _context.Doctors.AddAsync(doctor);
            await _context.SaveChangesAsync();


            var contactInfos = new List<(ContactType, string?)>
            {
                (ContactType.Email, doctorVM.Email),
                (ContactType.Phone, doctorVM.PhoneNumber),
                (ContactType.Facebook, doctorVM.SocialMediaFacebook),
                (ContactType.Twitter, doctorVM.SocialMediaTwitter)
            };

            Helpers.AddContactInfos(_context, OwnerType.Doctor, doctor.Id, contactInfos);

            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(List));
        }



        public async Task<IActionResult> Update(int? id)
        {

            if (id is null || id <= 0) return BadRequest();

            Doctor? doctor = await _context.Doctors.Include(d => d.Specialist).Include(d => d.WorkingHours).FirstOrDefaultAsync(d => d.Id == id);
            if (doctor is null) return NotFound();

            List<ContactInfo>? contactInfos = await _context.ContactInfos
                        .Where(c => c.OwnerType == OwnerType.Doctor && c.OwnerId == doctor.Id)
                        .ToListAsync();

            UpdateDoctorVM doctorVM = new UpdateDoctorVM
            {
                Name = doctor.Name.Capitalize(),
                Surname = doctor.Surname.Capitalize(),
                Age = doctor.Age,
                Gender = doctor.Gender,
                Email = contactInfos.FirstOrDefault(e => e.ContactType == ContactType.Email)?.Value,
                PhoneNumber = contactInfos.FirstOrDefault(x => x.ContactType == ContactType.Phone)?.Value,

MedishcMVCProject/Controllers/AboutUsController.cs
using MedishcMVCProject.DAL;
using MedishcMVCProject.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace MedishcMVCProject.Controllers
{
    public class AboutUsController : Controller
    {
        private readonly AppDbContext _context;

        public AboutUsController(AppDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> AboutUs()
        {
            HomeVM vm = new HomeVM()
            {
                Doctors = await _context.Doctors.Where(d => d.IsDeleted == false).Take(6).ToListAsync(),
                Specialists = await _context.Specialists.ToListAsync(),
                Clinics = await _context.Clinics.Where(c => c.IsDeleted == false).Take(3).ToListAsync(),
                ClinicServices = await _context.ClinicServices.Where(cs => cs.IsDeleted == false).ToListAsync(),
                Blogs = await _context.Blogs
                        .Include(b => b.BlogCategories)
                        .ThenInclude(bc => bc.Category)
                        .Where(b => b.IsDeleted == false)
                        .Take(6)
                        .ToListAsync(),
                Authors = await _context.Authors.Where(a => a.IsDeleted == false).ToListAsync(),
                Categories = await _context.Categories.Where(c => c.IsDeleted == false).ToListAsync()
            };
            return View(vm);
        }
        public async Task<IActionResult> MedicalServices()
        {
            AboutVM aboutVM = new AboutVM()
            {
                MedicalServices = await _context.MedicalServices.Take(6).ToListAsync(),
                Doctors = await _context.Doctors.Include(d => d.Specialist).Take(3).ToListAsync()
            };

            return View(aboutVM);
        }

        public IActionResult AboutService()
        {
            return View();
        }

        public async Task<IActionResult> Appointments()
        {
            AboutVM aboutVM = new AboutVM()
            {
                Doctors = await _context.Doctors.Include(d => d.Specialist).Take(3).ToListAsync()
            };

            return View(aboutVM);
        }

        public IActionResult PricingAndPlans()
        {
            return View();
        }
        public IActionResult FAQS()
        {
            return View();
        }
        public IActionResult Gallery()
        {
            return View();
        }
    }
}

MedishcMVCProject/Controllers/DoctorController.cs
using MedishcMVCProject.DAL;
using MedishcMVCProject.Models;
using MedishcMVCProject.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace MedishcMVCProject.Controllers
{
    public class DoctorController : Controller
    {
        private readonly AppDbContext _context;

        public DoctorController(AppDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {

            List<Doctor>? doctors = _context.Doctors
                                        .Include(d => d.Specialist)
                                        .Include(d => d.Degree)
                                        .Include(d => d.University)
                                        .ToList();

            DoctorIndexVM vm = new DoctorIndexVM
            {
                Doctors = doctors
            };

            return View(vm);


        }
        public async Task<IActionResult> DoctorDetail(int? id)
        {
            if (id is null || id <= 0) return BadRequest();

            Doctor? doctor = await _context.Doctors
                .Include(d => d.Specialist)
                .Include(d => d.Degree)
                .Include(d => d.University)
                .Include(d => d.PriceLists)
                .Include(d => d.WorkingHours)
                .FirstOrDefaultAsync(d => d.Id == id);

            if (doctor is null) return NotFound();

            DoctorDetailVM vm = new DoctorDetailVM()
            {
                Doctor = doctor,
                Degree = doctor.Degree,
                Specialist = doctor.Specialist,
                University = doctor.University,
                OpeningHours = doctor.WorkingHours.ToList(),
                PriceLists = doctor.PriceLists.ToList()
            };


            return View(vm);
        }
    }
}

MedishcMVCProject/Views/Doctor/Index.cshtml
@model DoctorIndexVM


<section class="hero hero-2 bg-overlay bg-overlay-dark">
    <div class="bg-section"> <img src="~/assets/images/sliders/1.jpg" alt="background" /></div>
    <div class="container">
        <div class="hero-content">
            <div class="row">
                <div class="col-12 col-lg-5">
                    <p class="hero-subtitle">The Best Medical And General Practice Care!</p>
                    <h2 class="hero-title">Delivering Tomorrow’s Care For Your Family.</h2>
                    <p class="hero-desc">Our doctors include highly qualified practitioners who come from a range of backgrounds and bring a diversity of skills. Our support staff all have exceptional people skills.</p>
                    <div class="hero-action"> <a class="btn btn--primary btn-line btn-line-after" asp-controller="AboutUs" asp-action="Appointments"> <span>make apponitment</span><span class="line"><span></span></span></a><a class="btn btn--white btn-line btn-line-after btn-line-inversed" asp-controller="AboutUs" asp-action="AboutUs"> <span>more about us</span><span class="line"><span></span></span></a></div>
                </div>
                <div class="col-12 col-lg-7">
                    <div class="hero-panel-holder">
                        <div class="hero-panel">
                            <div class="panel-content">
                                <i class="flaticon-028-book"></i>
                                <h5>doctors timetable</h5>
                                <p>Qualified doctors available six days a week, view our timetable to make an appointment.</p><a class="btn btn--white btn-line btn-line-before btn-line-inversed" href="#"> <span class="line"> <span> </span></span><span>view timetable</span></a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-12">
                    <ol class="breadcrumb d-flex">
                        <li class="breadcrumb-item"><a href="index.html">Home</a></li>
                        <li class="breadcrumb-item"><a href="#">doctors</a></li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
</section>
<!--
============================
Team Modern Section
============================
-->
<section class="team team-modern" id="teamModern">
    <div class="container">
        <div class="row">
            @foreach (var item in Model.Doctors)
            {
                <div class="col-12 col-md-6 col-lg-4">
                    <div class="team-member" data-hover="">
                        <div class="team-member-holder">
                            <div class="team-img"><a class="link" asp-action="DoctorDetail" asp-route-id="@item.Id"></a><img src="~/assets/images/team/grid/@item.Image" alt="team member" /></div>
                            <!-- End .team-img-->
                            <div class="team-content-holder">
                                <div class="team-content">
                                    <div class="team-title">
                                        <h4><a asp-action="DoctorDetail" asp-route-id="@item.Id">@item.Name @item.Surname</a></h4>
                                    </div>
                                    <div class="team-cat"><a href="#">@item.Specialist.Name Specialist</a></div>
                                    <div class="team-desc">
                                        <p>@item.MainDescription</p>
                                    </div>
                                    <div class="team-social"> <a href="javascript:void(0)"><i class="fab fa-facebook-f"> </i></a><a href="javascript:void(0)"><i class="fab fa-twitter"></i></a><a href="javascript:void(0)"><i class="fas fa-envelope"></i></a><a href="javascript:void(0)"><i class="fas fa-phone-alt"></i></a></div>
                                </div>
                                <!-- End .team-content-->
                            </div>
                        </div>
                    </div>
                </div>
            }
            
        </div>
        <!-- End .row-->
        <div class="row">
            <div class="col-12 clearfix text--center">
                <ul class="pagination">
                    <li><a class="current" href="javascript:void(0)">1</a></li>
                    <li><a href="javascript:void(0)">2</a></li>
                    <li><a href="#" aria-label="Next"><i class="icon-arrow-right"></i></a></li>
                </ul>
            </div>
        </div>
    </div>
    <!-- End .container-->
</section>
<!--
============================
Cta #2 Section
============================
-->
<section class="cta cta-2" id="cta-2">
    <div class="bg-section"><img src="~/assets/images/background/pattern.png" alt="background" /></div>
    <div class="container">
        <div class="heading heading-6">
            <div class="row">
                <div class="col-12 col-lg-5">
                    <p class="heading-subtitle">Caring For The Health Of You And Your Family.</p>
                </div>
            </div>
            <div class="row">
                <div class="col-12 col-lg-5">
                    <h2 class="heading-title">We Provide All Aspects Of Medical Practice For Your Whole Family!</h2>
                </div>
                <!--End .col-lg-5-->
                <div class="col-12 col-lg-6 offset-lg-1">
                    <div class="prief-set">
                        <p>We pride ourselves on providing the best transport and shipping services available allover the world. Our skilled personnal and processing software, combined with decades of experience! Through integrated supply chain solutions, Equita drives sustainable competitive advantages to some of Australia's largest companies.</p>
                        <ul class="list-unstyled advantages-list">
                            <li><i class="fas fa-check"></i> Quality Control System</li>
                            <li><i class="fas fa-check"></i> Unrivalled workmanship</li>
                            <li><i class="fas fa-check"></i> 100% Satisfaction Guarantee</li>
                        </ul>
                    </div>
                </div>
                <!--End .col-lg-6-->
            </div>
        </div>
        <div class="carousel owl-carousel" data-slide="6" data-slide-rs="2" data-autoplay="true" data-nav="false" data-dots="false" data-space="30" data-loop="true" data-speed="3000">
            <div class="certificate"><img class="img-fluid" src="~/assets/images/careers/1.png" alt="certificate" /></div>
            <div class="certificate"><img class="img-fluid" src="~/assets/images/careers/2.png" alt="certificate" /></div>
            <div class="certificate"><img class="img-fluid" src="~/assets/images/careers/3.png" alt="certificate" /></div>
            <div class="certificate"><img class="img-fluid" src="~/assets/images/careers/4.png" alt="certificate" /></div>
            <div class="certificate"><img class="img-fluid" src="~/assets/images/careers/5.png" alt="certificate" /></div>
            <div class="certificate"><img class="img-fluid" src="~/assets/images/careers/6.png" alt="certificate" /></div>
        </div>
    </div>
    <!-- End .container-->
</section>